defaults:
  - experiment: mos_gdps_metar
  - logging: debug
  - _self_

# Redirect outputs to a fixed directory to avoid scattering output dirs all across
# the filesystem.
hydra:
  run:
    dir: ${oc.env:SMC01_RUNS_DIR}/postprocessing/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:SMC01_RUNS_DIR}/postprocessing/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${oc.env:SLURM_JOB_ID,${hydra.job.num}}
  job:
    chdir: True


num_workers: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,4}}